const SHORT_MOVIE_DURATION = 40

const LARGE_WINDOW_INIT = 12;
const LARGE_WINDOW_STEP = 3;

const MEDIUM_WINDOW_SIZE = 1280;
const MEDIUM_WINDOW_INIT = 8;
const MEDIUM_WINDOW_STEP = 2;

const SMALL_WINDOW_SIZE = 682;
const SMALL_WINDOW_INIT = 5;
const SMALL_WINDOW_STEP = 2;

export {
  SHORT_MOVIE_DURATION,
  LARGE_WINDOW_INIT,
  LARGE_WINDOW_STEP,
  MEDIUM_WINDOW_SIZE,
  MEDIUM_WINDOW_INIT,
  MEDIUM_WINDOW_STEP,
  SMALL_WINDOW_SIZE,
  SMALL_WINDOW_INIT,
  SMALL_WINDOW_STEP,
};
